project: 
  name: stick.ai
  version: v0.1.1
  author: justwaitfor-me

game:
  stick: "|"
  max_sticks: 20

settings:
  debug: true

dqn_agent:
  learning_rate: 0.1    # Reduced for more stable learning
  discount_factor: 0.95   # Slightly reduced to focus on more immediate rewards

  epsilon_initial: 1.0
  epsilon_decay: 1.2    # Slower decay for better exploration
  epsilon_min: 0.01      # Increased minimum to maintain some exploration

  random_train_opponent: 0.7