project: 
  name: stick.ai
  version: v0.1.0
  author: justwaitfor-me

game:
  stick: "|"
  max_sticks: 20

settings:
  debug: true

dqn_agent:
  learning_rate: 0.1
  discount_factor: 0.99

  epsilon_initial: 1.0
  epsilon_decay: 0.9
  epsilon_min: 0.001

  random_train_opponent: 0.7